---
- name: Install Ruby and Bundler in packer image
  hosts: all
  become: true
  tasks:
    - name: Install Ruby and Bundler 
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - ruby-full
          - ruby-bundler
          - build-essential
