---
- name: Install MongoDB v. 3.2 in image
  hosts: all
  become: true
  tasks:
    - import_role:
        name: db
        #tasks_from: install_mongo.yml - Ограничить выполнение плейбука можно так, если не указывать теги в шаблоне пакера
