---
- name: Install Ruby and Bundler in packer image
  hosts: all
  become: true
  tasks:
    - import_role:
        name: app
        #tasks_from: ruby.yml - Ограничить выполнение плейбука можно так, если не указывать теги в шаблоне пакера
